/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT1_8 (coord A1), P1_8/J9[32]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN 8U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*! @name PORT1_9 (coord B1), P1_9/J9[30]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN 9U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEBUG_UART_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORT0_1 (coord A16), P0_1/SWCLK/J23[4]/D16[5]/J22[2]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDCLK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                                          /* @} */

/*! @name PORT0_0 (coord A17), P0_0/SWDIO/J23[2]/D16[6]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWDIO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                                         /* @} */

/*! @name PORT0_2 (coord B16), P0_2/SWO/J23[6]/D16[4]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITSWD_DEBUGPINS_DEBUG_SWD_SWO_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSWD_DEBUGPins(void);

/*! @name PORT1_2 (coord C4), P1_2/SJ4[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_INIT_GPIO_VALUE 0U       /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_BLUE_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_BLUE_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_10 (coord B12), P0_10/SJ5[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_RED_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_RED_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_RED_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_RED_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_RED_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT0_27 (coord E10), P0_27/SJ6[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN 27U              /*!<@brief GPIO pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITLEDSPINS_LED_GREEN_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN 27U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED_GREEN_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PORT0_6 (coord C14), P0_6/J23[7]/SW3[3]/SW3[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW3_GPIO GPIO0               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW3_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW3_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW3_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW3_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORT0_23 (coord B7), P0_23/SJ9[1]/SW2[3]/SW2[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONSPINS_SW2_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITBUTTONSPINS_SW2_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONSPINS_SW2_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_SW2_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_SW2_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PCR_IBE_ibe1 0x01u        /*!<@brief Input Buffer Enable: Enables */
#define PORT5_PCR_MUX_mux00 0x00u /*!<@brief Pin Multiplex Control: Alternative 0 (GPIO) */

/*! @name PORT0_14 (coord E11), P0_14/J4[6]/SJ19[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_14_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_14_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_14_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_14_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_14_PIN 14U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_14_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_15 (coord G13), P0_15/SJ8[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_15_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_15_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_15_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_15_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_15_PIN 15U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_15_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_22 (coord B8), P0_22/J4[8]/SJ18[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_22_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_22_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_22_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_22_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_22_PIN 22U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_22_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_24 (coord B6), P0_24/SJ7[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_24_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_24_GPIO_PIN 24U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_24_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_24_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_24_PIN 24U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_24_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_25 (coord A6), P0_25/J2[12]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_25_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_25_GPIO_PIN 25U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_25_GPIO_PIN_MASK (1U << 25U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_25_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_25_PIN 25U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_25_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_26 (coord F10), P0_26/J2[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_26_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_26_GPIO_PIN 26U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_26_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_26_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_26_PIN 26U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_26_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_28 (coord E8), P0_28/J2[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_28_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_28_GPIO_PIN 28U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_28_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_28_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_28_PIN 28U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_28_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_29 (coord F8), P0_29/J1[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_29_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_29_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_29_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_29_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_29_PIN 29U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_29_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_30 (coord E7), P0_30/SJ2[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_30_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_30_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_30_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_30_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_30_PIN 30U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_30_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT0_31 (coord D7), P0_31/J1[16]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P0_31_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P0_31_GPIO_PIN 31U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P0_31_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P0_31_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P0_31_PIN 31U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P0_31_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT1_0 (coord C6), P1_0/J5[6]/J2[17]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P1_00_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P1_00_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P1_00_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P1_00_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P1_00_PIN 0U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P1_00_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT1_1 (coord C5), P1_1/J5[5]/J2[15]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P1_01_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P1_01_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P1_01_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P1_01_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P1_01_PIN 1U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P1_01_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT1_12 (coord D2), P1_12/J2[11]/J9[28]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P1_12_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P1_12_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P1_12_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P1_12_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P1_12_PIN 12U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P1_12_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT1_21 (coord L5), P1_21/SJ3[1]/J1[7]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P1_21_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P1_21_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P1_21_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P1_21_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P1_21_PIN 21U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P1_21_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT1_22 (coord L4), P1_22/J9[24]/J3[3]/SJ9[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P1_22_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P1_22_GPIO_PIN 22U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P1_22_GPIO_PIN_MASK (1U << 22U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P1_22_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P1_22_PIN 22U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P1_22_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT1_23 (coord M4), P1_23/J9[23]/SJ1[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P1_23_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P1_23_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P1_23_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P1_23_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P1_23_PIN 23U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P1_23_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT2_0 (coord H2), P2_0/J3[1]/SJ8[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P2_00_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P2_00_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P2_00_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P2_00_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P2_00_PIN 0U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P2_00_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT2_2 (coord H3), P2_2/TP5/J12[8]/J3[7]/SJ7[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P2_02_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P2_02_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P2_02_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P2_02_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P2_02_PIN 2U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P2_02_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT2_3 (coord J3), P2_3/TP4/J12[7]/J3[5]/SJ4[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P2_03_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P2_03_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P2_03_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P2_03_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P2_03_PIN 3U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P2_03_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT2_4 (coord K3), P2_4/TP26/J12[5]/J3[11]/SJ5[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P2_04_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P2_04_GPIO_PIN 4U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P2_04_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P2_04_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P2_04_PIN 4U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P2_04_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT2_5 (coord K1), P2_5/TP25/J12[3]/J3[9]/SJ6[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P2_05_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P2_05_GPIO_PIN 5U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P2_05_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P2_05_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P2_05_PIN 5U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P2_05_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT2_6 (coord K2), P2_6/TP24/J12[2]/J3[15]/SJ1[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P2_06_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P2_06_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P2_06_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P2_06_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P2_06_PIN 6U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P2_06_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT2_7 (coord L2), P2_7/TP23/J12[1]/J3[13]/SJ3[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P2_07_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P2_07_GPIO_PIN 7U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P2_07_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P2_07_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P2_07_PIN 7U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P2_07_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT3_16 (coord J15), P3_16/SJ11[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P3_16_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P3_16_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P3_16_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P3_16_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P3_16_PIN 16U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P3_16_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_17 (coord K15), P3_17/J1[11]/SJ10[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P3_17_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P3_17_GPIO_PIN 17U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P3_17_GPIO_PIN_MASK (1U << 17U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P3_17_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P3_17_PIN 17U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P3_17_PIN_MASK (1U << 17U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_18 (coord K16), P3_18/J1[9]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P3_18_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P3_18_GPIO_PIN 18U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P3_18_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P3_18_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P3_18_PIN 18U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P3_18_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_19 (coord K17), P3_19/J5[1]/J1[13]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P3_19_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P3_19_GPIO_PIN 19U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P3_19_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P3_19_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P3_19_PIN 19U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P3_19_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_20 (coord M17), P3_20/J6[6]/J1[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P3_20_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P3_20_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P3_20_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P3_20_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P3_20_PIN 20U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P3_20_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT3_21 (coord L16), P3_21/J6[4]/J1[15]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P3_21_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P3_21_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P3_21_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P3_21_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P3_21_PIN 21U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P3_21_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT4_0 (coord P1), P4_0/J8[4]/SJ14[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_00_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_00_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_00_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_00_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_00_PIN 0U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_00_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT4_1 (coord P2), P4_1/J8[3]/SJ15[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_01_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_01_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_01_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_01_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_01_PIN 1U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_01_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT4_2 (coord T1), P4_2/J1[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_02_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_02_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_02_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_02_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_02_PIN 2U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_02_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT4_3 (coord U1), P4_3/J1[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_03_GPIO GPIO4               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_03_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_03_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_03_PORT PORT4               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_03_PIN 3U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_03_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT4_12 (coord T6), P4_12/SJ25[1]/J8[17]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_12_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_12_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_12_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_12_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_12_PIN 12U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_12_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT4_13 (coord T7), P4_13/SJ10[1]/SJ2[3]/J8[18]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_13_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_13_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_13_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_13_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_13_PIN 13U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_13_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT4_16 (coord R8), P4_16/SJ23[1]/J8[21]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_16_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_16_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_16_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_16_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_16_PIN 16U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_16_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT4_20 (coord T10), P4_20/SJ21[1]/J8[25]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P4_20_GPIO GPIO4                /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P4_20_GPIO_PIN 20U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P4_20_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P4_20_PORT PORT4                /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P4_20_PIN 20U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P4_20_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORT5_2 (coord M10), P5_2/SJ19[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P5_02_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P5_02_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P5_02_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P5_02_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P5_02_PIN 2U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P5_02_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*! @name PORT5_3 (coord N11), P5_3/SJ18[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define MCXN_KIT_P5_03_GPIO GPIO5               /*!<@brief GPIO peripheral base pointer */
#define MCXN_KIT_P5_03_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define MCXN_KIT_P5_03_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define MCXN_KIT_P5_03_PORT PORT5               /*!<@brief PORT peripheral base pointer */
#define MCXN_KIT_P5_03_PIN 3U                   /*!<@brief PORT pin number */
#define MCXN_KIT_P5_03_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void MCXN_KIT_Pins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
